[package]
name = "helpers"
version = "1.0.0"
edition = "2021"
resolver = "2"

[dependencies]
glam = { workspace = true }
num-traits = { workspace = true }
num-integer = { workspace = true }
rstest = { workspace = true }
