[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode"

[dependencies]
tera = "1"
chrono = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bin]]
name = "setup"
test = false
bench = false

[[bench]]
name = "day01"
harness = false

[[bench]]
name = "day02"
harness = false

[[bench]]
name = "day03"
harness = false
