[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
default-run = "adventofcode"

[dependencies]
tera = "1"
chrono = "0.4"
glam = "0.22.0"
lazy_static = "1.4.0"
regex = "1"
itertools = "0.10.3"
priority-queue = "1.2.1"
bitvec = "1.0.1"
hex = "0.4.3"
ptree = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
dotenv = "0.15.0"

[dev-dependencies]
criterion = "0.4.0"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "setup"
test = false
bench = false

[[bench]]
name = "day01"
harness = false

[[bench]]
name = "day02"
harness = false

[[bench]]
name = "day03"
harness = false

[[bench]]
name = "day04"
harness = false
