[package]
name = "setup"
version = "2023.0.0"
edition = "2021"
test = false
bench = false

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
tera = "1"
dotenv = "0.15.0"
color-eyre = { workspace = true }
