name: Advent of Code - Bechmark
on:
  schedule:
    - cron: "0 0 * * *"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v1
      - name: cargo-install
        uses: baptiste0928/cargo-install@v1.0.0
        with:
          crate: cargo-criterion
          version: latest
      - name: Build
        run: ./build-pgo.sh
      - name: Run benchmarks
        run: cargo criterion --verbose
        env:
          RUSTFLAGS: "-Cprofile-use=/tmp/pgo-data/merged.profdata -Ctarget-cpu=native"
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: ./target/criterion/reports/
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
